modLoader="javafml"
loaderVersion="[34,)"
updateJSONURL="https://raw.githubusercontent.com/MrCrayfish/ModUpdates/master/controllable/update.json"
issueTrackerURL="https://github.com/MrCrayfish/Controllable/issues"
displayURL="https://mrcrayfish.com/mods?id=controllable"
logoFile="controllable_logo.png"
authors="MrCrayfish"
license="GNU General Public License 3.0"

[[mods]]
modId="controllable"
version="0.13.2"
displayName="Controllable"
description="Adds the ability to use a controller to play Minecraft"

[[dependencies.controllable]]
   modId="forge"
   mandatory=true
   versionRange="[34.1.0,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.3,1.17)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="jei"
   mandatory=false
   versionRange="[7.6.0,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="configured"
   mandatory=false
   versionRange="[1.0.0,)"
   ordering="NONE"
   side="CLIENT"
[[dependencies.controllable]]
   modId="catalogue"
   mandatory=false
   versionRange="[1.2.0,)"
   ordering="NONE"
   side="CLIENT"

[modproperties.controllable]
   catalogueImageIcon="controllable_icon.png"
   configuredBackground="minecraft:textures/block/cobblestone.png"